import {
    ChangePassword,
    UserList,
    UserForm,
    Home,
    PartList,
    PartForm,
    DepartmentList,
    DepartmentForm,
    EUnitList,
    EUnitForm,
    FormatList,
    FormatForm,
    EmployeeList,
    EmployeeDetail,
    EmployeeForm,
    CourseForm,
    CourseList,
    ELevelList,
    ELevelForm,
    Login,
    Page404,
    ClassForm,
    ClassList,
    MajorList,
    MajorForm,
    HourForm,
    HourList,
} from '@/pages';

import { AuthLayout } from '@/layout';

//public Routes
const publicRoutes = [
    { path: '/home', component: Home },
    { path: '/login', component: Login, layout: AuthLayout },
    { path: '/', component: Login, layout: AuthLayout },
    { path: '*', component: Page404 },
    { path: '/class/update/:id', component: ClassForm },
    { path: '/class/create', component: ClassForm },
];

//private Routes
const privateRoutes = [
    { path: '/change-password', component: ChangePassword, requiredPermissions: ['User.ChangePassword'] },
    { path: '/users/list', component: UserList, requiredPermissions: ['Report.ViewSummaryList'] },
    { path: '/user/create', component: UserForm, requiredPermissions: ['User.ManageAccounts'] },
    { path: '/user/update/:id', component: UserForm, requiredPermissions: ['User.ManageAccounts'] },
    { path: '/parts/list', component: PartList, requiredPermissions: ['Part.Manage'] },
    { path: '/parts/list/all', component: PartList, requiredPermissions: ['Report.ViewSummaryList'] },
    { path: '/part/create', component: PartForm, requiredPermissions: ['Part.Manage'] },
    { path: '/part/update/:id', component: PartForm, requiredPermissions: ['Part.Manage'] },
    { path: '/departments/list', component: DepartmentList, requiredPermissions: ['Department.Manage'] },
    { path: '/departments/list/all', component: DepartmentList, requiredPermissions: ['Report.ViewSummaryList'] },
    { path: '/department/create', component: DepartmentForm, requiredPermissions: ['Department.Manage'] },
    { path: '/department/update/:id', component: DepartmentForm, requiredPermissions: ['Department.Manage'] },
    { path: '/eunits/list', component: EUnitList, requiredPermissions: ['Report.ViewSummaryList'] },
    { path: '/eunit/create', component: EUnitForm, requiredPermissions: ['TrainingUnit.Manage'] },
    { path: '/eunit/update/:id', component: EUnitForm, requiredPermissions: ['TrainingUnit.Manage'] },
    { path: '/formats/list', component: FormatList, requiredPermissions: ['Report.ViewSummaryList'] },
    { path: '/format/create', component: FormatForm, requiredPermissions: ['TrainingFormat.Manage'] },
    { path: '/format/update/:id', component: FormatForm, requiredPermissions: ['TrainingFormat.Manage'] },
    { path: '/employees/list', component: EmployeeList, requiredPermissions: ['Employee.Manage'] },
    { path: '/employees/list/all', component: EmployeeList, requiredPermissions: ['Report.ViewSummaryList'] },
    { path: '/employee/detail/:id', component: EmployeeDetail, requiredPermissions: ['Employee.Manage'] },
    { path: '/employee/create', component: EmployeeForm, requiredPermissions: ['Employee.Manage'] },
    { path: '/employee/update/:id', component: EmployeeForm, requiredPermissions: ['Employee.Manage'] },
    { path: '/course/create', component: CourseForm, requiredPermissions: ['Course.Manage'] },
    { path: '/course/update/:id', component: CourseForm, requiredPermissions: ['Course.Manage'] },
    { path: '/courses/list', component: CourseList, requiredPermissions: ['Course.Manage'] },
    { path: '/courses/list/all', component: CourseList, requiredPermissions: ['Report.ViewSummaryList'] },
    { path: '/elevels/list', component: ELevelList, requiredPermissions: ['EducationLevel.Manage'] },
    { path: '/elevel/create', component: ELevelForm, requiredPermissions: ['EducationLevel.Manage'] },
    { path: '/elevel/update/:id', component: ELevelForm, requiredPermissions: ['EducationLevel.Manage'] },
    { path: '/classes/list/', component: ClassList, requiredPermissions: ['Class.Manage'] },
    { path: '/classes/list/all', component: ClassList, requiredPermissions: ['Report.ViewSummaryList'] },
    { path: '/classes/list/longterm', component: ClassList, requiredPermissions: ['Class.Manage'] },
    { path: '/classes/list/shortterm', component: ClassList, requiredPermissions: ['Class.Manage'] },
    { path: '/class/create', component: ClassForm, requiredPermissions: ['Class.Manage'] },
    { path: '/class/update/:id', component: ClassForm, requiredPermissions: ['Class.Manage'] },
    { path: '/class/detail/:id', component: ClassForm, requiredPermissions: ['Class.Manage'] },
    { path: '/majors/list', component: MajorList, requiredPermissions: ['Report.ViewSummaryList'] },
    { path: '/major/create', component: MajorForm, requiredPermissions: ['Major.Manage'] },
    { path: '/major/update/:id', component: MajorForm, requiredPermissions: ['Major.Manage'] },
    { path: '/hour/update/:id', component: HourForm, requiredPermissions: ['CreditHourse.Manage'] },
    { path: '/hour/create', component: HourForm, requiredPermissions: ['CreditHourse.Manage'] },
    { path: '/hours/list', component: HourList, requiredPermissions: ['Report.ViewSummaryList'] },
];

export { publicRoutes, privateRoutes };
